safe: true
lsi: true
highlighter: rouge
markdown: kramdown
navigation:
  - text: Home
    url: /index.html
  - text: Imprint
    url: /imprint.html
baseurl: http://georg.io
imgbase: https://dl.dropboxusercontent.com/u/129945779/georgio
description: "Personal weblog of Georg R Walther. \
              Programming, data analysis, data visualization, machine learning, \
              modelling, dynamical systems, numerical analysis, and
              web applications in Python, C, and JavaScript."
author:
  name: Georg R Walther
  email: contact@georg.io
  nick: waltherg
  profiles:
    - label: GitHub
      url: https://github.com/waltherg
    - label: Twitter
      url: https://twitter.com/mbgrw
time: 2014-10-24
title: georg.io
permalink: /:year/:month/:title
relative_permalink: false
disqus:
  config:
    - label: disqus_shortname
      value: 'georgio'
googleanalytics:
  account: UA-45212489-1
plugins:
  - jekyll-seo-tag
twitter:
  username: mbgrw
social:
  name: Georg Walther
  links:
    - https://github.com/waltherg
    - https://twitter.com/mbgrw
    - https://www.linkedin.com/in/georgwalther
